experiment:
  id: ts_treenet
data:
  data_dir: /lustre/mlnvme/data/emarks1_hpc-data_fast/TreeNet3D_preprocessed
  dataloader: TreeNet3D
  varieties: ['Agarwood', 'ajianglanren', 'fenghuangmu', 'FloodedGum', 'Lemon', 'LombardyPoplar', 'shanshu', 'Tibetan_Cherry', 'xiaoyelanren', 'zhangshu']
  dataset_norm: true
  num_nodes: 15000
  num_points: 100000 # "auto"
  cond_resolution: 0.002
  node_resolution: 0.005
  node_count_vox_size: 0.12
  multiply_data: 50
  scan_farthps: false
  subsample_val: true
  debug_vis: false
diff:
  beta_start: 2.0e-06
  beta_end: 2.0e-04

train:
  batch_size: 4
  decay_lr: 0.0
  lr_decay_epochs: 75 #600
  lr: 0.0001
  uncond_w: 2.0
  input_feats: "semantics"
  use_colors: false
  use_semantics: true
  qsample_inference: true
  n_gpus: 1